# Copyright (c) 2021 Nordic Semiconductor ASA
# Copyright (c) 2024 Microchip Technology Inc.
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: origin
      url-base: https://github.com/MicrochipTech
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: origin
      revision: devel_mec5_all_updates
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - cmsis_6
    - name: hal_microchip
      path: modules/hal/microchip
      remote: origin
      revision: master
